import { buildSkeleton } from './marcBuilder.js';
import { validateRecord } from './marcValidator.js';
import { getRuleProfile, hasMarcRule, normalizeMarcTag } from './marcRuleRegistry.js';
import { findBundledClass, buildPath } from './ddcKnowledgeBase.js';
import { buildKohaFillPlan } from './kohaMapper.js';

const SOURCE_DERIVED = 'SOURCE_DERIVED';
const RULE_DERIVED = 'RULE_DERIVED';
const CATALOGUER_APPROVED = 'CATALOGUER_APPROVED';

// Tags this module mechanically constructs in buildAdditionalFields, beyond
// the skeleton marcBuilder.js emits. Declared here so marcConsistency.js can
// count them as builder-covered instead of flagging SUPPORTED_BUT_BUILDER_MISSING.
// 005 is deliberately absent: it is a Koha/system-managed control field and
// is never generated by AutoCat (see EXCLUDED_CONTROL_TAGS below).
export function getPipelineEmittedTags() {
  return ['336', '337', '338', '440'];
}

// Product requirement: 000, 005, 008 and 942 must never appear in AutoCat's
// generated MARC payload -- not in `fields`, not in the preview, not in the
// Koha fill plan. 000/008 are simply never built (marcBuilder.js), 005 is
// simply never appended (buildAdditionalFields below), and 942 is never
// generated anywhere in this codebase. This filter is defense in depth so a
// future change to any of those paths (or a stray LOC-sourced field) can
// never let one of these four tags leak into a downstream consumer.
const EXCLUDED_CONTROL_TAGS = new Set(['000', '005', '008', '942']);

function excludeKohaManagedFields(fields) {
  return fields.filter((f) => !EXCLUDED_CONTROL_TAGS.has(normalizeMarcTag(f.tag)));
}

export function normalizeIsbn(value) {
  const raw = String(value ?? '').replace(/[-\s]/g, '').toUpperCase();
  if (/^\d{9}[0-9X]$/.test(raw)) return isbn10To13(raw);
  return raw;
}

function isbn10To13(isbn10) {
  const prefixed = `978${isbn10.slice(0, 9)}`;
  let sum = 0;
  for (let i = 0; i < 12; i += 1) sum += Number(prefixed[i]) * (i % 2 === 0 ? 1 : 3);
  return `${prefixed}${(10 - (sum % 10)) % 10}`;
}

export function isValidIsbn(value) {
  const isbn = String(value ?? '').replace(/[-\s]/g, '').toUpperCase();
  if (/^\d{9}[0-9X]$/.test(isbn)) {
    const sum = isbn.split('').reduce((acc, ch, idx) => acc + (ch === 'X' ? 10 : Number(ch)) * (10 - idx), 0);
    return sum % 11 === 0;
  }
  if (/^\d{13}$/.test(isbn)) {
    const sum = isbn.split('').reduce((acc, ch, idx) => acc + Number(ch) * (idx % 2 === 0 ? 1 : 3), 0);
    return sum % 10 === 0;
  }
  return false;
}

function cleanText(value) { return String(value ?? '').trim(); }
function array(value) { return Array.isArray(value) ? value.filter(Boolean) : value ? [value] : []; }
function first(value) { return array(value)[0] ?? null; }

// A research/AI step occasionally returns a "description" that is really
// just a citation artifact -- literally "Source title: <title>" or "Title:
// <title>" -- or a bare restatement of the title/series (with nothing else
// added), never an actual summary of the book's content. 520$a must never
// contain that: it's not evidence of what the book is ABOUT, just an echo
// of a field this record already has elsewhere. Rejected here (returns '')
// rather than passed through -- 520 is simply omitted when this is all that
// was supplied, exactly like any other genuinely-missing evidence case,
// never patched with a fabricated summary.
const JUNK_DESCRIPTION_PREFIX_RE = /^(?:source\s+title|title|book\s+title)\s*:/i;

function sanitizeDescription(description, title) {
  const text = cleanText(description);
  if (!text) return '';
  if (JUNK_DESCRIPTION_PREFIX_RE.test(text)) return '';
  const bareTitle = cleanText(title).toLowerCase();
  // Strip a trailing "(Series Name)" parenthetical before comparing -- a
  // description that's just "<Title> (<Series>)" carries no more content
  // than the title alone.
  const withoutTrailingParens = text.replace(/\s*\([^()]*\)\s*$/, '').trim();
  if (bareTitle && withoutTrailingParens.toLowerCase() === bareTitle) return '';
  return text;
}

// Subject cleanup: exact- and near-duplicate removal, THEN a hard cap of 7
// 650 fields (product spec: "Generate MAXIMUM 7 subject headings. Never
// more than 7."). "Autism", "Autism in children", and "Autism spectrum
// disorders" are all distinct valid headings and all survive dedup; only
// genuine duplicates (same heading restated with different casing,
// whitespace, trailing punctuation, or a trivial plural) collapse to one.
// Callers (the research/AI reasoning layer -- see isbnLookup.js /
// ddcAiClassifier.js) are responsible for supplying `subjects` already
// ordered most-relevant-first; this deterministic layer never re-ranks by
// content, it only removes noise/duplicates and truncates to the best 7 in
// the order it received them -- never pads to reach 7 when fewer genuinely
// exist.
const MAX_SUBJECTS = 7;
const NOISE_SUBJECT_RE = /^(?:https?:\/\/|www\.|search results?$|untitled$|n\/a$|\d+$)/i;

// Comparison-only key for near-duplicate detection -- never used as the
// stored/displayed value. Two subjects collapse to one entry only when they
// normalize to the SAME key (same words, modulo case/punctuation/trivial
// pluralization), never merely because one contains the other -- a broader
// or narrower heading that shares words with an already-kept one (e.g.
// "Autism" vs "Autism in children") has a different key and is kept.
function subjectDedupeKey(subject) {
  return subject
    .toLowerCase()
    .trim()
    .replace(/[.,;:]+$/, '')
    .replace(/\s+/g, ' ')
    .replace(/s$/, '');
}

function filterSubjects(subjects) {
  const seen = new Set();
  const out = [];
  for (const subject of subjects) {
    const trimmed = subject.trim();
    if (trimmed.length < 2 || NOISE_SUBJECT_RE.test(trimmed)) continue;
    const key = subjectDedupeKey(trimmed);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(trimmed);
  }
  return out.slice(0, MAX_SUBJECTS);
}

export function normalizeMarcMetadata(input = {}) {
  const metadata = input.metadata ?? input;
  const normalized = {
    isbn: normalizeIsbn(metadata.isbn),
    title: cleanText(metadata.title),
    subtitle: cleanText(metadata.subtitle),
    authors: array(metadata.authors ?? metadata.author).map(cleanText),
    editors: array(metadata.editors).map(cleanText),
    illustrators: array(metadata.illustrators).map(cleanText),
    translators: array(metadata.translators).map(cleanText),
    publisher: cleanText(metadata.publisher),
    publication_place: cleanText(metadata.publication_place),
    publish_date: cleanText(metadata.publish_date ?? metadata.publication_date),
    edition: cleanText(metadata.edition),
    // A source occasionally nests series as { name } (e.g. Open Library's
    // raw shape before extraction) rather than a plain string -- accept
    // either, same defensive read the extension's own display code already
    // does (sidepanel.js's bookDetailsHtml).
    series: cleanText(typeof metadata.series === 'object' ? metadata.series?.name : metadata.series),
    language: cleanText(metadata.language ?? metadata.language_code),
    subjects: filterSubjects(array(metadata.subjects ?? metadata.subject_headings).map(cleanText).filter(Boolean)),
    description: sanitizeDescription(metadata.description ?? metadata.abstract, metadata.title),
    notes: array(metadata.notes).map(cleanText),
    bibliography_note: cleanText(metadata.bibliography_note),
    awards: array(metadata.awards).map(cleanText),
    urls: array(metadata.urls ?? metadata.url).map(cleanText),
    physical_description: metadata.physical_description ?? {},
    sources: metadata.sources ?? {},
  };
  return normalized;
}

export function detectMetadataConflicts(sources = {}) {
  const conflicts = [];
  const comparable = ['title', 'publisher', 'publish_date', 'edition'];
  for (const field of comparable) {
    const values = Object.entries(sources)
      .map(([source, data]) => ({ source, value: cleanText(data?.[field]) }))
      .filter((entry) => entry.value);
    const unique = [...new Map(values.map((v) => [v.value.toLowerCase(), v])).values()];
    if (unique.length > 1) {
      conflicts.push({ field, status: 'CONFLICT', preferred: unique[0], alternatives: unique.slice(1), evidence: values });
    }
  }
  return conflicts;
}

function withProvenance(field, source, provenance) {
  return { ...field, source, provenance, validation_status: 'UNVALIDATED' };
}

function dataField(tag, subfields, indicators = [' ', ' '], source = 'metadata', provenance = SOURCE_DERIVED) {
  return withProvenance({ tag, indicators, subfields }, source, provenance);
}

function languageCode(language) {
  const value = cleanText(language).toLowerCase();
  if (!value) return null;
  if (/^[a-z]{3}$/.test(value)) return value;
  const map = { english: 'eng', malayalam: 'mal', hindi: 'hin', tamil: 'tam', sanskrit: 'san' };
  return map[value] ?? null;
}

// extractSurname/toSurnameFirst -- product spec item 30: a personal-name
// 1xx/7xx $a must be "Surname, First name", never a trailing full stop
// (unlike title/publication fields, which DO end in ISBD punctuation).
// Source data (isbnLookup.js's authors/editors/etc arrays) is plain
// "First Last" strings from every source this app queries, so this always
// reformats rather than trusting a source to already be surname-first --
// except when a name already contains a comma, which is treated as already
// being in that form and left alone (just stripped of a trailing stop).
function extractSurname(fullName) {
  const name = cleanText(fullName);
  if (!name) return null;
  if (name.includes(',')) return cleanText(name.split(',')[0]);
  const parts = name.split(/\s+/).filter(Boolean);
  return parts.length ? parts[parts.length - 1] : null;
}

function toSurnameFirst(fullName) {
  const name = cleanText(fullName).replace(/\.\s*$/, '');
  if (!name) return null;
  if (name.includes(',')) return name;
  const parts = name.split(/\s+/).filter(Boolean);
  if (parts.length < 2) return name || null;
  const surname = parts[parts.length - 1];
  const given = parts.slice(0, -1).join(' ');
  return `${surname}, ${given}`;
}

// cutterFromSurname -- product spec item 29/33: 082$b is the first three
// CAPITAL letters of the author/editor/compiler surname.
function cutterFromSurname(fullName) {
  const surname = extractSurname(fullName);
  if (!surname) return null;
  const letters = surname.replace(/[^A-Za-z]/g, '').toUpperCase().slice(0, 3);
  return letters || null;
}

// Contributors who are evidenced (isbnLookup.js's editors/illustrators/
// translators arrays, plus any author beyond the single 100 main entry)
// but were previously dropped entirely unless LOC's own MARC record
// happened to already carry them -- product spec items 27/29/36: real
// evidence must not be silently discarded just because no AI-drafting step
// runs for 7xx. Relator terms/codes are the standard MARC relator list
// (https://www.loc.gov/marc/relators/), not invented.
const RELATOR_TERMS = {
  editors: { term: 'editor', code: 'edt' },
  illustrators: { term: 'illustrator', code: 'ill' },
  translators: { term: 'translator', code: 'trl' },
};

function build700Fields(metadata) {
  if (!hasMarcRule('700')) return [];
  const fields = [];
  for (const coAuthor of metadata.authors.slice(1)) {
    const formatted = toSurnameFirst(coAuthor);
    if (formatted) fields.push(dataField('700', [{ code: 'a', value: formatted }], ['1', ' ']));
  }
  for (const [key, { term, code }] of Object.entries(RELATOR_TERMS)) {
    for (const name of metadata[key]) {
      const formatted = toSurnameFirst(name);
      if (!formatted) continue;
      fields.push(
        dataField('700', [{ code: 'a', value: formatted }, { code: 'e', value: term }, { code: '4', value: code }], ['1', ' '])
      );
    }
  }
  return fields;
}

// RDA 336/337/338 -- content/media/carrier type. Unlike every other field
// in this function, these are never derived from research evidence: they
// describe the fundamental FORM of the resource (text, printed, bound
// volume), not a fact about this particular book, so there is nothing here
// to fabricate. AutoCat only ever catalogues printed monographs (the whole
// pipeline -- 300$a page counts, [S.l.]/AACR2-style 260, etc. -- already
// assumes this), so the standard RDA vocabulary for a physical printed
// book applies uniformly, exactly like 008's fixed-field defaults
// (RULE_DERIVED, not SOURCE_DERIVED). Terms/codes are the controlled RDA
// content/media/carrier lists (https://www.loc.gov/standards/valuelist/).
function build336to338Fields() {
  const fields = [];
  if (hasMarcRule('336')) {
    fields.push(dataField('336', [{ code: 'a', value: 'text' }, { code: 'b', value: 'txt' }, { code: '2', value: 'rdacontent' }], [' ', ' '], 'rule', RULE_DERIVED));
  }
  if (hasMarcRule('337')) {
    fields.push(dataField('337', [{ code: 'a', value: 'unmediated' }, { code: 'b', value: 'n' }, { code: '2', value: 'rdamedia' }], [' ', ' '], 'rule', RULE_DERIVED));
  }
  if (hasMarcRule('338')) {
    fields.push(dataField('338', [{ code: 'a', value: 'volume' }, { code: 'b', value: 'nc' }, { code: '2', value: 'rdacarrier' }], [' ', ' '], 'rule', RULE_DERIVED));
  }
  return fields;
}

function buildAdditionalFields(metadata) {
  const fields = [];
  fields.push(...build336to338Fields());
  const lang = languageCode(metadata.language);
  if (lang && hasMarcRule('041')) fields.push(dataField('041', [{ code: 'a', value: lang }]));
  // 440 -- series (rules/marc_runtime_rules.json's series_policy: this
  // AutoCat profile targets 440, never silently 490/8xx). Only generated
  // when a source actually supplied a series title -- never fabricated;
  // absent when the evidence simply doesn't include one.
  if (metadata.series && hasMarcRule('440')) fields.push(dataField('440', [{ code: 'a', value: metadata.series }], [' ', '0']));
  if (metadata.description && hasMarcRule('520')) fields.push(dataField('520', [{ code: 'a', value: metadata.description }], [' ', ' ']));
  for (const note of metadata.notes) if (hasMarcRule('500')) fields.push(dataField('500', [{ code: 'a', value: note }]));
  if (metadata.bibliography_note && hasMarcRule('504')) fields.push(dataField('504', [{ code: 'a', value: metadata.bibliography_note }]));
  for (const award of metadata.awards) if (hasMarcRule('586')) fields.push(dataField('586', [{ code: 'a', value: award }]));
  for (const subject of metadata.subjects) if (hasMarcRule('650')) fields.push(dataField('650', [{ code: 'a', value: subject }], [' ', '0']));
  for (const url of metadata.urls) if (/^https?:\/\//i.test(url) && hasMarcRule('856')) fields.push(dataField('856', [{ code: 'u', value: url }], ['4', '0']));
  const mainAuthor = first(metadata.authors);
  if (mainAuthor && hasMarcRule('100')) {
    const formatted = toSurnameFirst(mainAuthor);
    if (formatted) fields.push(dataField('100', [{ code: 'a', value: formatted }], ['1', ' ']));
  }
  fields.push(...build700Fields(metadata));
  return fields;
}

// ddcUnavailable -- DDC classification simply hasn't produced a number yet
// (the normal PENDING state before any recommendation exists, or after a
// genuine INSUFFICIENT_EVIDENCE result). There is no separate "cataloguer
// approval" gate in this product -- ddcApprovalService.saveDdcDecision
// auto-accepts a recommendation the moment one exists, so "not APPROVED"
// here never means "waiting for a human to click approve"; it means
// classification hasn't reached a number. That must never block the rest
// of an otherwise-good MARC record: 082 is simply omitted, reported as
// info (not a validation error), and READY_FOR_KOHA/Fill MARC stay
// available for every other field.
function ddcUnavailable(message) {
  return { ok: false, errors: [], info: [{ level: 'CATALOGUING_PROFILE', code: 'DDC_NOT_AVAILABLE', tag: '082', message }], field: null };
}

// ddcFailure -- a GENUINE data-integrity problem: a decision claims
// APPROVED but the number itself doesn't check out (missing, unknown to
// the DDC knowledge base, unassigned, or an unresolvable hierarchy). This
// is the one case that should still block the record -- a bad 082 must
// never silently reach Koha.
function ddcFailure(code, message) { return { ok: false, errors: [{ level: 'DDC_APPROVAL', code, tag: '082', message }], info: [], field: null }; }

export function buildApproved082(ddcApproval = {}, ruleProfile = getRuleProfile(), cutterSourceName = null) {
  if (!ddcApproval || ddcApproval.approval_status !== 'APPROVED') {
    return ddcUnavailable('DDC 23 classification is not available for this record yet -- 082 omitted.');
  }
  const approved = cleanText(ddcApproval.approved_ddc);
  if (!approved) return ddcFailure('APPROVED_DDC_MISSING', 'Approved DDC number is missing.');
  const ddcClass = findBundledClass(approved);
  if (!ddcClass) return ddcFailure('DDC_NOT_FOUND', `Approved DDC ${approved} is not in the DDC knowledge base.`);
  if (ddcClass.status !== 'ASSIGNED') return ddcFailure('DDC_NOT_ASSIGNED', `Approved DDC ${approved} has status ${ddcClass.status}.`);
  const path = buildPath(approved);
  if (path.length === 0 || path[0] !== ddcClass.main_class) return ddcFailure('DDC_HIERARCHY_UNRESOLVED', `Approved DDC ${approved} hierarchy could not be resolved.`);
  const edition = ruleProfile?.ddc_edition_default || '23';
  const subfields = [{ code: 'a', value: approved }];
  const cutter = cutterFromSurname(cutterSourceName);
  if (cutter) subfields.push({ code: 'b', value: cutter });
  subfields.push({ code: '2', value: String(edition).replace(/\D/g, '') || '23' });
  return { ok: true, errors: [], info: [], field: dataField('082', subfields, ['0', '4'], 'ddc_decision', CATALOGUER_APPROVED), ddc_class: ddcClass };
}

// The final MARC field array must always be in numeric tag order (000,
// 005, 008, 020, ..., 856, 942) regardless of what order the skeleton
// builder / AI reasoning / DDC step happened to push fields in -- upstream
// this is currently assembled as skeleton fields, then evidence-driven
// fields (440/500/520/650/856/100/700 -- 100 notably pushed AFTER 650/700),
// then 082 last, none of which is numeric order. Consumers (marcPreview,
// the Koha fill plan, the admin record view) must never rely on that
// incidental construction order, and a librarian-facing preview listing
// 700 before 100 before 245 reads as broken even when every field is
// individually correct. Array.prototype.sort is stable (ECMA-262 since
// ES2019), so repeatable tags (multiple 650/700) keep their original
// relative order -- never reordered or deduplicated against each other.
function sortFieldsByTag(fields) {
  return [...fields].sort((a, b) => Number(normalizeMarcTag(a.tag)) - Number(normalizeMarcTag(b.tag)));
}

function toStructuredRecord(fields) {
  const leader = fields.find((f) => normalizeMarcTag(f.tag) === '000');
  return {
    leader: leader?.subfields?.[0]?.value ?? null,
    controlFields: fields.filter((f) => ['005', '008'].includes(normalizeMarcTag(f.tag))).map((f) => ({ tag: normalizeMarcTag(f.tag), value: f.subfields?.[0]?.value ?? f.value ?? '', source: f.source, provenance: f.provenance })),
    dataFields: fields.filter((f) => !['000', '005', '008'].includes(normalizeMarcTag(f.tag))).map((f) => ({ tag: normalizeMarcTag(f.tag), ind1: f.indicators?.[0] ?? ' ', ind2: f.indicators?.[1] ?? ' ', subfields: f.subfields ?? [], source: f.source, provenance: f.provenance })),
  };
}

function marcPreview(fields, validation) {
  return fields.map((field) => {
    const tag = normalizeMarcTag(field.tag);
    const status = validation.fields?.[tag]?.valid === false ? 'ERROR' : validation.fields?.[tag]?.warnings?.length ? 'WARNING' : 'OK';
    const indicators = field.indicators?.[0] == null ? '' : `${field.indicators[0]}${field.indicators[1]}`;
    const body = (field.subfields ?? []).map((sf) => (sf.code ? `$${sf.code} ${sf.value}` : sf.value)).join(' ');
    return { tag, indicators, value: body, source: field.source ?? 'unknown', provenance: field.provenance ?? 'UNKNOWN', validation_status: status };
  });
}

export function generateMarcRecord(input = {}, options = {}) {
  const ruleProfile = options.ruleProfile ?? getRuleProfile();
  const metadata = normalizeMarcMetadata(input.metadata ?? input);
  // PUBLICATION_DEBUG (product spec item 7/21) -- confirms whether
  // publication_place/publisher/publish_date actually reached the MARC
  // builder, so a [S.l.] in 260$a can be traced to "the research pipeline
  // found no place" (evidence=false below) rather than "the builder lost
  // it" (which this line would otherwise leave silently unprovable).
  console.info(
    `PUBLICATION_DEBUG isbn=${metadata.isbn || 'null'} publication_place=${metadata.publication_place || 'null'} publisher=${metadata.publisher || 'null'} publish_date=${metadata.publish_date || 'null'} evidence=${Boolean(metadata.publication_place)}`
  );
  const conflicts = detectMetadataConflicts(input.sources ?? metadata.sources);
  const isUnverifiedWebMetadata = ['web_search', 'web_scrape', 'agent_research', 'page'].includes(metadata.sources?.method);
  const skeleton = buildSkeleton(metadata, ruleProfile).skeleton.map((f) => withProvenance(f, isUnverifiedWebMetadata ? 'metadata_unverified' : 'metadata', f.tag === '040' ? RULE_DERIVED : SOURCE_DERIVED));
  const fields = [...skeleton, ...buildAdditionalFields(metadata)];
  const ddc = buildApproved082(input.ddc_approval ?? input.ddcDecision ?? {}, ruleProfile, first(metadata.authors));
  const ddcErrors = ddc.errors;
  const ddcInfo = ddc.info ?? [];
  if (ddc.ok) fields.push(ddc.field);
  // Canonical numeric tag order from here on -- every downstream consumer
  // (validation, the structured record, the preview, the Koha fill plan)
  // reads this same sorted array, so there is exactly one field order, not
  // a different one per consumer. 000/005/008/942 are stripped here too --
  // never generated in practice, but excluded defensively so they can never
  // reach validation, the preview, or the Koha fill plan (see
  // EXCLUDED_CONTROL_TAGS above).
  const sortedFields = sortFieldsByTag(excludeKohaManagedFields(fields));
  const ddcApproval = input.ddc_approval ?? input.ddcDecision ?? {};
  const validation = validateProductionMarc(sortedFields, { metadata, ddcApproval, ddcErrors, ddcInfo });
  const marcRecord = toStructuredRecord(sortedFields);
  const result = { metadata, marc_record: marcRecord, fields: sortedFields, validation, preview: marcPreview(sortedFields, validation), provenance: sortedFields.map((f) => ({ tag: normalizeMarcTag(f.tag), source: f.source, provenance: f.provenance })), conflicts, status: validation.valid ? 'READY_FOR_KOHA' : 'REQUIRES_CATALOGUER_REVIEW' };
  // P4: only offer a Koha fill plan once the record validates. An invalid
  // record must not produce fill instructions.
  result.koha_fill = validation.valid ? buildKohaFillPlan(result, { ddcApproval }) : null;
  return result;
}

export function validateProductionMarc(fields, { metadata = {}, ddcApproval = {}, ddcErrors = [], ddcInfo = [] } = {}) {
  const base = validateRecord(fields);
  const errors = base.issues.map((issue) => ({ level: 'STRUCTURAL', ...issue }));
  const warnings = [];
  const info = [...ddcInfo];
  const byTag = Object.groupBy(fields, (f) => normalizeMarcTag(f.tag));
  if (metadata.isbn && !isValidIsbn(metadata.isbn)) errors.push({ level: 'CATALOGUING_PROFILE', tag: '020', code: 'INVALID_ISBN', message: '020$a must contain a valid ISBN-10 or ISBN-13.' });
  const marc020 = byTag['020']?.flatMap((f) => f.subfields ?? []).find((sf) => sf.code === 'a')?.value;
  if (marc020 && !isValidIsbn(marc020)) errors.push({ level: 'CATALOGUING_PROFILE', tag: '020', code: 'INVALID_020_ISBN', message: 'MARC 020$a is ISBN only and must validate as ISBN.' });
  if (ddcErrors.length) errors.push(...ddcErrors);
  const has082 = Boolean(byTag['082']?.some((f) => (f.subfields ?? []).some((sf) => sf.code === 'a')));
  if (has082 && ddcApproval.approval_status !== 'APPROVED') errors.push({ level: 'DDC_APPROVAL', tag: '082', code: '082_WITHOUT_APPROVAL', message: '082$a cannot be present without APPROVED DDC.' });
  if (metadata.language) {
    const lang = languageCode(metadata.language);
    if (!lang) warnings.push({ level: 'EVIDENCE', tag: '041', code: 'LANGUAGE_NOT_CODED', message: 'Language evidence was supplied but could not be mapped to a MARC code.' });
  }
  if (!byTag['246'] && hasMarcRule('246')) info.push({ level: 'CATALOGUING_PROFILE', tag: '246', code: 'NOT_AUTOMATED', message: '246 remains controlled by runtime status and is not fabricated by P3.' });
  // 440 IS generated automatically (see buildAdditionalFields) -- its
  // absence here just means no source supplied series evidence for this
  // record, never that the field is unimplemented. Informational only,
  // never blocking: fabricating a series would violate the "never invent
  // evidence" rule far more than simply having no series to report.
  if (!byTag['440'] && hasMarcRule('440')) info.push({ level: 'CATALOGUING_PROFILE', tag: '440', code: 'NO_SERIES_EVIDENCE', message: 'No series evidence was found for this record -- 440 omitted, not fabricated.' });
  const fieldsResult = {};
  for (const f of fields) {
    const tag = normalizeMarcTag(f.tag);
    fieldsResult[tag] = { valid: !errors.some((e) => e.tag === tag), warnings: warnings.filter((w) => w.tag === tag) };
  }
  return { valid: errors.length === 0, errors, warnings, info, fields: fieldsResult, base_scope: base.scope, levels: ['STRUCTURAL', 'CATALOGUING_PROFILE', 'EVIDENCE', 'DDC_APPROVAL'] };
}
